FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install
COPY . .
ARG DATABASE_URL
ARG STORE_NAME
ARG STORE_ADDRESS
ARG STORE_CONTACT
ENV DATABASE_URL=$DATABASE_URL
ENV STORE_NAME=$STORE_NAME
ENV STORE_ADDRESS=$STORE_ADDRESS
ENV STORE_CONTACT=$STORE_CONTACT

RUN npx prisma generate

# ENV NEXT_IGNORE_TYPE_ERRORS=true

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
