name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Read version from package.json
        id: version
        run: echo "VERSION=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -t ghcr.io/erwindggr/basicpos:latest \
            -t ghcr.io/erwindggr/basicpos:${{ env.VERSION }} .

      - name: Push Docker images (latest + versioned)
        run: |
          docker push ghcr.io/erwindggr/basicpos:latest
          docker push ghcr.io/erwindggr/basicpos:${{ env.VERSION }}
